# Generated by Django 4.2.6 on 2023-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_sign_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
