version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8030 multisys.wsgi:application
    #command: python manage.py runserver 0.0.0.0:8030
    volumes:
      - .:/app
    ports:
      - "8030:8030"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_DOCKER_HOST}

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 multisys.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_DOCKER_HOST}

networks:
  multisystem_back_default:
    driver: bridge
