version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8030 multisys.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8030:8030"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - multisystem_back_default
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}

#  nginx:
#    image: nginx:latest
#    ports:
#      - "8080:80"
#    depends_on:
#      - web
#    volumes:
#      - /root/multisystem_sqllite3:/etc/nginx/conf.d:ro

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - multisystem_back_default

networks:
  multisystem_back_default:
    driver: bridge
