@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class "Node7" as node7
class "Node15" as node15
class "Node26" as node26
class "Node110" as node110
class "Node128" as node128
class "Node137" as node137
class "Node154" as node154
class "Node157" as node157

class APIView
class AbstractUser
class AppConfig
class CreateAPIView
class CronJobBase
class FilterSet
class ImportExportModelAdmin
class ListAPIView
class ListCreateAPIView
class Model
class ModelAdmin
class ModelResource
class ModelSerializer
class ModelViewSet
class PageNumberPagination
class PermissionsMixin
class RetrieveAPIView
class RetrieveUpdateAPIView
class RetrieveUpdateDestroyAPIView
class TextChoices
class UpdateAPIView
class UserChangeForm
class View
class node124 as "apps.depo.admin.IncomingAdmin"
class node143 as "apps.depo.admin.IncomingDetailAdmin"
class node13 as "apps.depo.admin.OutgoingAdmin"
class node36 as "apps.depo.admin.OutgoingMaterialAdmin"
class node115 as "apps.depo.admin.StockAdmin"
class node28 as "apps.depo.apps.DepoConfig"
class node79 as "apps.depo.models.incoming.Incoming"
class node42 as "apps.depo.models.incoming.IncomingMaterial"
class node145 as "apps.depo.models.outgoing.Outgoing"
class node112 as "apps.depo.models.outgoing.OutgoingMaterial"
class node126 as "apps.depo.models.stock.Stock"
class node82 as "apps.depo.serializers.IncomingListOnlySerializer"
class node106 as "apps.depo.serializers.IncomingMaterialSerializer"
class node77 as "apps.depo.serializers.IncomingSerializer"
class node151 as "apps.depo.serializers.OutgoingListOnlySerializer"
class node18 as "apps.depo.serializers.OutgoingMaterialSerializer"
class node121 as "apps.depo.serializers.OutgoingSerializer"
class node63 as "apps.depo.serializers.StockSerializer"
class node117 as "apps.depo.views.incoming.IncomingCreateView"
class node114 as "apps.depo.views.incoming.IncomingDetailView"
class node14 as "apps.depo.views.incoming.IncomingListView"
class node10 as "apps.depo.views.incoming.IncomingMaterialListView"
class node41 as "apps.depo.views.outgoing.OutgoingCreateView"
class node119 as "apps.depo.views.outgoing.OutgoingDetailView"
class node86 as "apps.depo.views.outgoing.OutgoingListView"
class node155 as "apps.depo.views.outgoing.OutgoingMaterialListView"
class node29 as "apps.depo.views.stock.StockDetailView"
class node142 as "apps.depo.views.stock.StockListView"
class node103 as "apps.depo.views.stock.UnacceptedMaterialsDetailView"
class node136 as "apps.depo.views.stock.UnacceptedMaterialsListView"
class node34 as "apps.hr.admin.DepartmentAdmin"
class node46 as "apps.hr.admin.DivisionAdmin"
class node50 as "apps.hr.admin.EmployeeAdmin"
class node1 as "apps.hr.admin.PositionAdmin"
class node84 as "apps.hr.apps.HrConfig"
class node109 as "apps.hr.cron.SendDailyReport"
class node70 as "apps.hr.models.Department"
class node150 as "apps.hr.models.Division"
class node94 as "apps.hr.models.Employee"
class node148 as "apps.hr.models.Position"
class node72 as "apps.hr.serializers.DepartmentSerializer"
class node92 as "apps.hr.serializers.DivisionSerializer"
class node147 as "apps.hr.serializers.EmployeeSerializer"
class node54 as "apps.hr.serializers.PositionSerializer"
class node100 as "apps.hr.views.DailyReport"
class node8 as "apps.hr.views.DepartmentListCreateView"
class node16 as "apps.hr.views.DivisionsListCreateView"
class node69 as "apps.hr.views.EmployeeDetailUpdateDeleteView"
class node38 as "apps.hr.views.EmployeeListCreateView"
class node47 as "apps.hr.views.EmployeePDFExportView"
class node0 as "apps.hr.views.PositionListCreateView"
class node101 as "apps.info.admin.BrandAdmin"
class node131 as "apps.info.admin.CurrencyAdmin"
class node156 as "apps.info.admin.DeviceAdmin"
class node73 as "apps.info.admin.FirmAdmin"
class node146 as "apps.info.admin.MaterialAdmin"
class node88 as "apps.info.admin.MaterialGroupAdmin"
class node132 as "apps.info.admin.MaterialPartyAdmin"
class node89 as "apps.info.admin.MaterialTypeAdmin"
class node24 as "apps.info.admin.SpecificationAdmin"
class node90 as "apps.info.admin.UnitAdmin"
class node91 as "apps.info.admin.WarehouseAdmin"
class node144 as "apps.info.apps.InfoConfig"
class node105 as "apps.info.models.Brand"
class node120 as "apps.info.models.Currency"
class node97 as "apps.info.models.Dealer"
class node59 as "apps.info.models.Device"
class node111 as "apps.info.models.Firm"
class node127 as "apps.info.models.Material"
class node125 as "apps.info.models.MaterialGroup"
class node58 as "apps.info.models.MaterialParty"
class node68 as "apps.info.models.MaterialType"
class node65 as "apps.info.models.Specification"
class node140 as "apps.info.models.Unit"
class node116 as "apps.info.models.Warehouse"
class node95 as "apps.info.resources.MaterialResource"
class node60 as "apps.info.serializers.infos.BrandSerializer"
class node6 as "apps.info.serializers.infos.CurrencySerializer"
class node2 as "apps.info.serializers.infos.DealerSerializer"
class node37 as "apps.info.serializers.infos.DeviceSerializer"
class node98 as "apps.info.serializers.infos.FirmSerializer"
class node30 as "apps.info.serializers.infos.SpecSerializer"
class node158 as "apps.info.serializers.infos.UnitSerializer"
class node152 as "apps.info.serializers.material.MaterialGroupSerializer"
class node33 as "apps.info.serializers.material.MaterialPartySerializer"
class node129 as "apps.info.serializers.material.MaterialSerializer"
class node153 as "apps.info.serializers.material.MaterialTypeSerializer"
class node141 as "apps.info.serializers.warehouse.WarehouseSerializer"
class node130 as "apps.info.views.infos.BrandViewSetView"
class node11 as "apps.info.views.infos.CurrencyViewSetView"
class node78 as "apps.info.views.infos.DealerViewSetView"
class node39 as "apps.info.views.infos.DeviceViewSetView"
class node40 as "apps.info.views.infos.FirmViewSetView"
class node21 as "apps.info.views.infos.SpecificationViewSetView"
class node44 as "apps.info.views.infos.UnitViewSetView"
class node55 as "apps.info.views.material.MaterialGroupViewSetView"
class node75 as "apps.info.views.material.MaterialTypeViewSetView"
class node74 as "apps.info.views.material.MaterialViewSetView"
class node12 as "apps.info.views.warehouse.WarehouseViewSetView"
class node159 as "apps.purchase.admin.PurchaseAdmin"
class node31 as "apps.purchase.admin.PurchaseProductAdmin"
class node81 as "apps.purchase.apps.PurchaseConfig"
class node71 as "apps.purchase.models.Purchase"
class node32 as "apps.purchase.models.PurchaseProduct"
class node118 as "apps.purchase.models.PurchaseStatus"
class node20 as "apps.purchase.serializers.PurchaseListOnlySerializer"
class node49 as "apps.purchase.serializers.PurchaseProductSerializer"
class node122 as "apps.purchase.serializers.PurchaseSerializer"
class node87 as "apps.purchase.views.AssignPurchaseView"
class node96 as "apps.purchase.views.AssignedPurchaseListView"
class node45 as "apps.purchase.views.ConfirmedPurchaseListView"
class node102 as "apps.purchase.views.PurchaseConfirmationView"
class node61 as "apps.purchase.views.PurchaseCreateView"
class node4 as "apps.purchase.views.PurchaseDetailView"
class node83 as "apps.purchase.views.PurchaseListView"
class node85 as "apps.shared.admin.DailyReportAdmin"
class node35 as "apps.shared.apps.SharedConfig"
class node52 as "apps.shared.filters.PurchaseFilter"
class node57 as "apps.shared.models.BaseModel"
class node93 as "apps.shared.models.DailyReport"
class node27 as "apps.shared.serializers.BaseNameCodeSerializer"
class node67 as "apps.shared.utils.CustomPagination"
class node76 as "apps.shared.views.BaseListView"
class node3 as "apps.users.admin.CustomUserAdmin"
class node133 as "apps.users.apps.UsersConfig"
class node62 as "apps.users.forms.CustomUserChangeForm"
class node104 as "apps.users.models.CustomUser"
class node139 as "apps.users.serializers.CustomUserSerializer"
class node138 as "apps.users.views.UsersListView"

node124                       ^-[#595959,plain]-  ModelAdmin
node143                       ^-[#595959,plain]-  ModelAdmin
node13                        ^-[#595959,plain]-  ModelAdmin
node36                        ^-[#595959,plain]-  ModelAdmin
node115                       ^-[#595959,plain]-  ModelAdmin
node28                        ^-[#595959,plain]-  AppConfig
node79                        ^-[#595959,plain]-  node57
node42                        ^-[#595959,plain]-  Model
node145                       ^-[#595959,plain]-  node57
node112                       ^-[#595959,plain]-  Model
node126                       ^-[#595959,plain]-  Model
node82                        ^-[#595959,plain]-  ModelSerializer
node106                       ^-[#595959,plain]-  ModelSerializer
node77                        ^-[#595959,plain]-  ModelSerializer
node151                       ^-[#595959,plain]-  ModelSerializer
node18                        ^-[#595959,plain]-  ModelSerializer
node121                       ^-[#595959,plain]-  ModelSerializer
node63                        ^-[#595959,plain]-  ModelSerializer
node117                       ^-[#595959,plain]-  CreateAPIView
node114                       ^-[#595959,plain]-  RetrieveAPIView
node14                        ^-[#595959,plain]-  node76
node10                        ^-[#595959,plain]-  ListAPIView
node41                        ^-[#595959,plain]-  CreateAPIView
node119                       ^-[#595959,plain]-  RetrieveAPIView
node86                        ^-[#595959,plain]-  node76
node155                       ^-[#595959,plain]-  ListAPIView
node29                        ^-[#595959,plain]-  RetrieveAPIView
node142                       ^-[#595959,plain]-  node76
node103                       ^-[#595959,plain]-  APIView
node136                       ^-[#595959,plain]-  ListAPIView
node34                        ^-[#595959,plain]-  ModelAdmin
node46                        ^-[#595959,plain]-  ModelAdmin
node50                        ^-[#595959,plain]-  ModelAdmin
node1                         ^-[#595959,plain]-  ModelAdmin
node84                        ^-[#595959,plain]-  AppConfig
node109                       ^-[#595959,plain]-  CronJobBase
node70                        ^-[#595959,plain]-  node57
node150                       ^-[#595959,plain]-  Model
node94                        ^-[#595959,plain]-  node57
node148                       ^-[#595959,plain]-  node57
node72                        ^-[#595959,plain]-  ModelSerializer
node92                        ^-[#595959,plain]-  ModelSerializer
node147                       ^-[#595959,plain]-  ModelSerializer
node54                        ^-[#595959,plain]-  ModelSerializer
node100                       ^-[#595959,plain]-  View
node8                         ^-[#595959,plain]-  ListCreateAPIView
node16                        ^-[#595959,plain]-  ListCreateAPIView
node69                        ^-[#595959,plain]-  RetrieveUpdateDestroyAPIView
node38                        ^-[#595959,plain]-  ListCreateAPIView
node38                        ^-[#595959,plain]-  node76
node47                        ^-[#595959,plain]-  View
node0                         ^-[#595959,plain]-  ListCreateAPIView
node101                       ^-[#595959,plain]-  ModelAdmin
node131                       ^-[#595959,plain]-  ModelAdmin
node156                       ^-[#595959,plain]-  ModelAdmin
node73                        ^-[#595959,plain]-  ModelAdmin
node146                       ^-[#595959,plain]-  ImportExportModelAdmin
node146                       ^-[#595959,plain]-  ModelAdmin
node88                        ^-[#595959,plain]-  ModelAdmin
node132                       ^-[#595959,plain]-  ModelAdmin
node89                        ^-[#595959,plain]-  ModelAdmin
node24                        ^-[#595959,plain]-  ModelAdmin
node90                        ^-[#595959,plain]-  ModelAdmin
node91                        ^-[#595959,plain]-  ModelAdmin
node144                       ^-[#595959,plain]-  AppConfig
node105                       ^-[#595959,plain]-  node57
node120                       ^-[#595959,plain]-  node57
node97                        ^-[#595959,plain]-  node57
node59                        ^-[#595959,plain]-  node57
node111                       ^-[#595959,plain]-  node57
node127                       ^-[#595959,plain]-  node57
node125                       ^-[#595959,plain]-  Model
node58                        ^-[#595959,plain]-  node57
node68                        ^-[#595959,plain]-  Model
node65                        ^-[#595959,plain]-  node57
node140                       ^-[#595959,plain]-  Model
node116                       ^-[#595959,plain]-  node57
node95                        ^-[#595959,plain]-  ModelResource
node60                        ^-[#595959,plain]-  ModelSerializer
node6                         ^-[#595959,plain]-  ModelSerializer
node2                         ^-[#595959,plain]-  ModelSerializer
node37                        ^-[#595959,plain]-  ModelSerializer
node98                        ^-[#595959,plain]-  node27
node30                        ^-[#595959,plain]-  ModelSerializer
node158                       ^-[#595959,plain]-  node27
node152                       ^-[#595959,plain]-  node27
node33                        ^-[#595959,plain]-  ModelSerializer
node129                       ^-[#595959,plain]-  node27
node153                       ^-[#595959,plain]-  node27
node141                       ^-[#595959,plain]-  node27
node130                       ^-[#595959,plain]-  ModelViewSet
node11                        ^-[#595959,plain]-  ModelViewSet
node78                        ^-[#595959,plain]-  ModelViewSet
node39                        ^-[#595959,plain]-  ModelViewSet
node40                        ^-[#595959,plain]-  ModelViewSet
node21                        ^-[#595959,plain]-  ModelViewSet
node44                        ^-[#595959,plain]-  ModelViewSet
node55                        ^-[#595959,plain]-  ModelViewSet
node75                        ^-[#595959,plain]-  ModelViewSet
node74                        ^-[#595959,plain]-  ModelViewSet
node12                        ^-[#595959,plain]-  ModelViewSet
node159                       ^-[#595959,plain]-  ModelAdmin
node31                        ^-[#595959,plain]-  ModelAdmin
node81                        ^-[#595959,plain]-  AppConfig
node71                        ^-[#595959,plain]-  node57
node32                        ^-[#595959,plain]-  Model
node118                       ^-[#595959,plain]-  TextChoices
node20                        ^-[#595959,plain]-  ModelSerializer
node49                        ^-[#595959,plain]-  ModelSerializer
node122                       ^-[#595959,plain]-  ModelSerializer
node87                        ^-[#595959,plain]-  UpdateAPIView
node96                        ^-[#595959,plain]-  ListAPIView
node45                        ^-[#595959,plain]-  ListAPIView
node102                       ^-[#595959,plain]-  RetrieveUpdateAPIView
node61                        ^-[#595959,plain]-  CreateAPIView
node4                         ^-[#595959,plain]-  RetrieveAPIView
node83                        ^-[#595959,plain]-  node76
node85                        ^-[#595959,plain]-  ModelAdmin
node35                        ^-[#595959,plain]-  AppConfig
node52                        ^-[#595959,plain]-  FilterSet
node57                        ^-[#595959,plain]-  Model
node93                        ^-[#595959,plain]-  Model
node27                        ^-[#595959,plain]-  ModelSerializer
node67                        ^-[#595959,plain]-  PageNumberPagination
node76                        ^-[#595959,plain]-  ListAPIView
node3                         ^-[#595959,plain]-  ModelAdmin
node133                       ^-[#595959,plain]-  AppConfig
node62                        ^-[#595959,plain]-  UserChangeForm
node104                       ^-[#595959,plain]-  AbstractUser
node104                       ^-[#595959,plain]-  PermissionsMixin
node139                       ^-[#595959,plain]-  ModelSerializer
node138                       ^-[#595959,plain]-  node76
@enduml
