# Generated by Django 4.2.6 on 2023-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
