# Generated by Django 4.2.6 on 2023-11-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaseproduct_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='accepted_at',
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase'),
        ),
    ]
