# Generated by Django 4.2.6 on 2023-11-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('purchase', '0005_remove_purchaseproduct_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchases', to='hr.employee'),
        ),
    ]
