# Generated by Django 4.2.6 on 2023-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchase_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='distributed_at',
            new_name='assigned_at',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('assigned', 'Распределена'), ('rejected', 'Отклонена'), ('delivered', 'Доставлена'), ('in_stock', 'В складе')], default='new'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('assigned', 'Распределена'), ('rejected', 'Отклонена'), ('accepted', 'Принята'), ('delivered', 'Доставлена'), ('in_stock', 'В складе')], default='new'),
        ),
    ]
