# Generated by Django 4.2.6 on 2023-12-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='division',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='position',
            name='menu',
        ),
        migrations.DeleteModel(
            name='HrMenu',
        ),
    ]
