# Generated by Django 4.2.6 on 2023-10-18 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number_series',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_pin',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='report_card',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=999999)]),
        ),
    ]
