# Generated by Django 4.2.6 on 2023-10-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_material_party_number_materialparty_and_more'),
        ('depo', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailoutgoing',
            name='material_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.materialparty'),
        ),
        migrations.AlterField(
            model_name='incomingdetail',
            name='material_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.materialparty'),
        ),
    ]
