# Generated by Django 4.2.6 on 2023-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Отклонен', 'Отклонен'), ('В ожидании', 'В ожидании')], default=None),
        ),
    ]
