# Generated by Django 4.2.6 on 2023-11-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='amount',
        ),
    ]
