# Generated by Django 4.2.6 on 2023-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='outgoing_materials',
            field=models.ManyToManyField(blank=True, related_name='outgoing_materials', to='depo.outgoingmaterial'),
        ),
    ]
