# Generated by Django 4.2.6 on 2023-11-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0004_remove_stock_material_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoing',
            old_name='data',
            new_name='date',
        ),
    ]
