# Generated by Django 4.2.6 on 2023-11-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0004_outgoing_outgoing_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='outgoing_materials',
        ),
    ]
