# Generated by Django 4.2.6 on 2023-10-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_material_party_number_materialparty_and_more'),
        ('depo', '0004_alter_detailoutgoing_material_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.warehouse'),
        ),
    ]
