# Generated by Django 4.2.6 on 2023-11-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_warehouse_can_export'),
        ('depo', '0004_remove_incoming_status_outgoing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='material_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.materialparty'),
        ),
    ]
