# Generated by Django 4.2.6 on 2023-10-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_material_party_number_materialparty_and_more'),
        ('depo', '0005_stock_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.warehouse'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='available_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='material_party',
        ),
    ]
