# Generated by Django 4.2.6 on 2023-11-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0005_rename_data_outgoing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoing',
            old_name='date',
            new_name='data',
        ),
    ]
