# Generated by Django 4.2.6 on 2023-10-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('depo', '0006_alter_stock_unique_together_stock_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailoutgoing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='detailoutgoing',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='detailoutgoing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='detailoutgoing',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='incomingdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incomingdetail',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='incomingdetail',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='incomingdetail',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='incoming',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='incomingdetail',
            name='purchase_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseproduct'),
        ),
    ]
