# Generated by Django 4.2.6 on 2023-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0006_alter_outgoing_id_alter_outgoing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
