# Generated by Django 4.2.6 on 2023-11-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0006_rename_date_outgoing_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='type',
            new_name='incoming_type',
        ),
    ]
