# Generated by Django 4.2.6 on 2023-11-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0007_alter_stock_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoing',
            old_name='type',
            new_name='outgoing_type',
        ),
    ]
