# Generated by Django 4.2.6 on 2023-10-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_material_party_number_materialparty_and_more'),
        ('depo', '0007_remove_detailoutgoing_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailOutgoing',
            new_name='OutgoingDetail',
        ),
    ]
