# Generated by Django 4.2.6 on 2023-11-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_material_material_party'),
        ('depo', '0007_rename_type_incoming_incoming_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='incoming_materials',
            field=models.ManyToManyField(blank=True, related_name='incoming_materials', to='depo.incomingmaterial'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='outgoing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='depo.outgoing'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_warehouse', to='info.warehouse'),
        ),
    ]
