# Generated by Django 4.2.6 on 2023-11-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0008_incoming_incoming_materials_alter_incoming_outgoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='outgoing_materials',
            field=models.ManyToManyField(blank=True, related_name='outgoing_materials', to='depo.outgoingmaterial'),
        ),
        migrations.AlterField(
            model_name='outgoingmaterial',
            name='outgoing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.outgoing'),
        ),
    ]
