# Generated by Django 4.2.6 on 2023-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0009_outgoing_outgoing_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='incoming_materials',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='outgoing_materials',
        ),
        migrations.AlterField(
            model_name='outgoingmaterial',
            name='outgoing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_materials', to='depo.outgoing'),
        ),
    ]
