# Generated by Django 4.2.6 on 2023-11-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_materialparty_production_date'),
        ('depo', '0010_remove_incoming_incoming_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmaterial',
            name='material_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.materialparty'),
        ),
    ]
