# Generated by Django 4.2.6 on 2024-01-26 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount_of_employee', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=9999)])),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, unique=True)),
                ('report_card', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=999999)])),
                ('badge_number', models.CharField(max_length=10, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_hire', models.DateField()),
                ('is_fired', models.BooleanField(default=False)),
                ('date_of_fire', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')])),
                ('date_of_birth', models.DateField()),
                ('passport_number_series', models.CharField(max_length=10, unique=True)),
                ('passport_issued_by', models.CharField(max_length=255)),
                ('passport_when_issued', models.DateField()),
                ('passport_pin', models.CharField(max_length=14, unique=True)),
                ('photo', models.ImageField(default='default-profile__picture.jpg', upload_to='employee_photos')),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
    ]
