# Generated by Django 4.2.6 on 2023-10-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
