# Generated by Django 4.2.6 on 2023-11-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_specification_options_specification_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_party',
        ),
    ]
