# Generated by Django 4.2.6 on 2023-10-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_delete_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='party_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='size_and_shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='warranty',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
