# Generated by Django 4.2.6 on 2023-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_material_material_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialparty',
            name='production_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
