# Generated by Django 4.2.6 on 2023-10-19 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_material_note_material_party_number_material_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_imei', message='IMEI должен состоять из 16 цифр.', regex='^\\d{16}$')]),
        ),
    ]
